services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.26-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: db
    image: mysql:8.4.4
    volumes:
      - ./database/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'
    ports:
      - '8025:8025'
      - '1025:1025'
